<?php

namespace AppBundle\Repository;

/**
 * MessageQuereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageQueueRepository extends \Doctrine\ORM\EntityRepository
{
}
