<?php

namespace AppBundle\Repository;

/**
 * TravelOrderMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravelOrderMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
