<?php

namespace AppBundle\Repository;

/**
 * TravelServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravelServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
