<?php

namespace AppBundle\Repository;

/**
 * TravelOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravelOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
