<?php

namespace AppBundle\Repository;

/**
 * TravelScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravelScoreRepository extends \Doctrine\ORM\EntityRepository
{
}
